services:
  solr:
    image: solr:latest
    container_name: my-solr
    ports:
      - "8983:8983"
    environment:
      - SOLR_HEAP=512m
      - SOLR_OPTS=-Dsolr.lock.type=native
    volumes:
      - solr_data:/var/solr/data
      - ./my_custom_core:/var/solr/data/my_custom_core
    command: >
      bash -c "
        if [ ! -f /var/solr/data/my_custom_core/core.properties ]; then
          solr-precreate my_custom_core /var/solr/data/my_custom_core/conf --user-managed;
        fi &&
        solr-foreground
      "
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: my-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: sampledb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_CHARACTER_SET_SERVER: utf8mb4
      MYSQL_COLLATION_SERVER: utf8mb4_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --init-connect="SET NAMES utf8mb4"



volumes:
  solr_data:
  mysql_data: